name: Healthcheck

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  scheduled_health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: Run a health check on the deployed Heroku app
        uses: jtalk/url-health-check-action@v1.2
        with:
          url: https://fullstack-cicd.herokuapp.com
          follow-redirect: no
          max-attempts: 3
          retry-delay: 5s
