name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Run npm install
        run: npm install
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: E2E tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Deploy to heroku
        uses: akhileshns/heroku-deploy@v3.8.8 # This is the action
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'fullstack-cicd' #Must be unique in Heroku
          heroku_email: 'pontus.hedlund@gmail.com'
          healthcheck: 'https://fullstack-cicd.herokuapp.com/version'
          checkstring: '1'
          rollbackonhealthcheckfailed: true

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.33.0
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

      - name: Announce success on Slack
        uses: 8398a7/action-slack@v3
        with:
          status: success
          fields: repo, commit, author, took
          custom_payload: |
            {
              attachments: [{
                color: 'good',
                text: `a new version deployed to Heroku (${process.env.AS_COMMIT}) by ${process.env.AS_AUTHOR} build took ${process.env.AS_TOOK}`
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') && success() }}

      - name: Announce failure on Slack
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          fields: repo, message, commit, author, action
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') && failure() }}
